[SUPABASE]
URL = "postgresql://postgres.dmucssgskmhpqdkyovwc:ClickLog2026@aws-1-sa-east-1.pooler.supabase.com:6543/postgres"
KEY = sb_publishable_sfUWEI0jRY36Hh1iRGeDEA_6MaBTPIy
SENHA_EMAIL = "gdheyfidavrsslbh"